#**How to select the regression  Model?**(based on Dataset)

In [ ]:
import numpy as np 
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt 
import pandas as pd 

In [ ]:
data = pd.read_csv('Data.csv')

In [ ]:
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [ ]:
x = data.iloc[:,:-1].values
x 

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [ ]:
y = data.iloc[:,-1].values
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

##**Split Train and Test**

In [ ]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(x,y ,test_size = 0.2,random_state=0)

##**Multiple Regression**

In [ ]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
ypred_lin = lin_reg.predict(x_test)
print(ypred_lin)

[431.42761597 458.56124622 462.75264705 ... 469.51835895 442.41759454
 461.88279939]


In [ ]:
print(r2_score(y_test, ypred_lin))

0.9325315554761303


##**Polynomial Regression**

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 2)
poly.fit(x_train)
xpoly = poly.transform(x_train)
xpoly

array([[1.00000000e+00, 1.12200000e+01, 4.31300000e+01, ...,
        1.03477722e+06, 8.22947160e+04, 6.54481000e+03],
       [1.00000000e+00, 1.36700000e+01, 5.43000000e+01, ...,
        1.03209345e+06, 7.66206864e+04, 5.68817640e+03],
       [1.00000000e+00, 3.28400000e+01, 7.79500000e+01, ...,
        1.02957550e+06, 4.64723440e+04, 2.09764000e+03],
       ...,
       [1.00000000e+00, 1.68100000e+01, 3.85200000e+01, ...,
        1.03685343e+06, 7.65833346e+04, 5.65654410e+03],
       [1.00000000e+00, 1.28000000e+01, 4.11600000e+01, ...,
        1.04536310e+06, 8.81232417e+04, 7.42871610e+03],
       [1.00000000e+00, 3.23200000e+01, 6.79000000e+01, ...,
        1.01219697e+06, 3.81606144e+04, 1.43868490e+03]])

In [ ]:
from sklearn.linear_model import LinearRegression
lin_regpoly = LinearRegression()
lin_regpoly.fit(xpoly,y_train)

LinearRegression()

In [ ]:
ypred_linpoly = lin_regpoly.predict(poly.transform(x_test))
print(ypred_linpoly)

[432.76953308 457.41440837 462.02307275 ... 468.9193898  441.35683597
 461.1246669 ]


In [ ]:
print(r2_score(y_test, ypred_linpoly))

0.9421687659462465


##**SVM Regression**

In [ ]:
from sklearn.preprocessing  import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
sc_x.fit(x_train)
sc_y.fit(y_train.reshape(-1,1))


StandardScaler()

In [ ]:
sc_y.transform(y_train.reshape(-1,1))

array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [ ]:
y_train.reshape(1,len(y_train))

array([[473.93, 467.87, 431.97, ..., 459.01, 462.72, 428.12]])

In [ ]:
from sklearn.svm import SVR
svr_reg = SVR(kernel='rbf')
svr_reg.fit(sc_x.transform(x_train),sc_y.transform(y_train.reshape(-1,1)))

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
ypred_svr = svr_reg.predict(sc_x.transform(x_test))
ypred_svr = sc_y.inverse_transform(ypred_svr.reshape(-1,1))
print(ypred_svr)

[[434.05242921]
 [457.93810186]
 [461.03113894]
 ...
 [470.60268461]
 [439.41653548]
 [460.91757115]]


In [ ]:
print(r2_score(y_test, ypred_svr))

0.9480784049986258


##**Desision Tree Regression**

In [ ]:
from sklearn.tree import DecisionTreeRegressor 
des_reg = DecisionTreeRegressor(random_state = 2 )
des_reg.fit(x_train,y_train)

In [ ]:
ypred_des = des_reg.predict(x_test)
print(ypred_des)

In [ ]:
print(r2_score(y_test, ypred_des))

##**Random Foerest Regression**

In [ ]:
from sklearn.ensemble import RandomForestRegressor 
ran_reg = RandomForestRegressor(n_estimators= 10,random_state = 2 )
ran_reg.fit(x_train,y_train)

In [ ]:
ypred_ran = ran_reg.predict(x_test)
print(ypred_ran)

In [ ]:
print(r2_score(y_test, ypred_ran))