#**Artificial Neural Networks**

feature scaling is must in Deep learning

In [121]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import tensorflow as tf 

In [122]:
tf.__version__

'2.12.0'

##**Data-Preprocessing**

In [123]:
data = pd.read_csv('/content/Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [124]:
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values 

In [125]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [126]:
y

array([1, 0, 1, ..., 1, 1, 0])

##**Encoding Categorical Data**

###**Label Encoding**

In [127]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [128]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


###**One Hot Encoding**

In [129]:
type(x)

numpy.ndarray

In [130]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])] ,remainder='passthrough' ) 
x = np.array(ct.fit_transform(x))

In [131]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


##**Splitting data into Test and Training Set**

In [132]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.2,random_state = 0)

In [133]:
x_train.shape

(8000, 12)

In [134]:
y_train.shape

(8000,)

##**Feature Scaling**

In [135]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [136]:
print(x_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


#**Building ANN**

###**Initializing the ANN**

In [137]:
#initializes the ANN as sequence of layes 
ann = tf.keras.models.Sequential()

###**Adding the input layer and the first hidden Layer**

In [138]:
#add a fully connnected layer as the object of the dense class
#how many layers do we want>it's random   
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))
  

###**Adding the second hidden layer**

In [139]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

###**Adding the output layer**

In [140]:
ann.add(tf.keras.layers.Dense(units = 1 , activation='sigmoid'))

##**Training the Artifical Neural Network**

##**Compiling the ANN**

In [141]:
#using adam optimizer 
#non binary = categorical_crossentropy 
#metrics
ann.compile(optimizer ='adam' , loss ='binary_crossentropy' ,metrics=['accuracy'] )

In [155]:
#number of predection in batch_size 
#An epoch means training the neural network with all the training data for one cycle. In an epoch, we use all of the data exactly once. A forward pass and a backward pass together are counted as one pass: An epoch is made up of one or more batches, where we use a part of the dataset to train the neural network.
ann.fit(x_train,y_train,batch_size = 32 ,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3308 - accuracy: 0.8660
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 0.8650
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3309 - accuracy: 0.8669
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8635
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 0.8651
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3308 - accuracy: 0.8643
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8641
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3306 - accuracy: 0.8659
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8655
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3314 - accura

##**Making predection and Evaluating the model**

###**Making Individual predection**

In [148]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 31ms/step
[[False]]


###**Training set** 

In [149]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 2ms/step


In [150]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [151]:
from sklearn.metrics import confusion_matrix ,accuracy_score 
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1500   95]
 [ 186  219]]


In [153]:
acc = accuracy_score(y_test, y_pred)
acc

0.8595